### ISSUE TITLE
Can't be detected in VESC Tool latest versions

### ISSUE THREAD

**Issue by gedesu** [dakhnod/NRF51-serial-multitool#1]
Hello,

Doesn't show up in latest VESC Tool versions. Doesn't work i think this is something related to the different UUID's of Nordic UART service .

Thanks, keep up the good work.

**Comment by dakhnod** [comment]
Mine is also using BLE UART, supporting two different profiles. Probably something with the device name...

**Comment by gedesu** [comment]
Tried changing name from "Serial adapter" to "VESC BLE UART" didn't helped either. Doesn't get detected in "VESC tool". What type is Your VESC tool version, becouse old VESC tools use old HM-10 with SPP (serial port profile) and not BLE UART service.  Used NRF51 firmware from https://github.com/vedderb/nrf51_vesc repo it works and is detected in VESC tool - perfectly fine, so not module fault. With original Benjamin firmware Nordic UART service UUID shows up as 0x2902.
Also want to ask about RGB LED's how can it be controlled, i mean RGB color switching, enabling, syncing?

**Comment by dakhnod** [comment]
Could you please try again with the latest release and commit? It works for me now.

Also, you can easily control APA102 leds with this code, since the led's speak SPI, while having their own protocol.
Writing something like 0x00 0x00 0x00 0x00 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0xff should make the first led light up white or something...

**Comment by gedesu** [comment]
Now it's detected perfectly fine. 

10x
